### ISSUE TITLE
Images do not load correctly in fullscreen

### ISSUE THREAD

**Issue by kosi2801** [vanita5/twittnuker#82] opened 2016-03-20 11:51 UTC
Since a few weeks it appears more and more that images are shown in small but when enlarged to fullscreen the image doesn't load and the screen keeps black.

**Comment by ianweller** [comment] 2016-03-24 04:01
I have this issue as well. I think it has to do with certain PNGs (possibly based on the presence of an alpha channel?) -- camera photos seem to always load fine, whereas some screenshots and digital artwork don't display okay.

I'll try and provide some examples of tweets with media that do and don't work.

**Comment by alerque** [comment] 2016-04-06 08:48
Same thing here, but I had kind of concluded that it was some sort of intolerance for network issues because sortimes they would work on killing the app or being on a different link.

**Comment by vanita5** [comment] 2016-04-06 16:31
Is this problem still present with the last update?

**Comment by alerque** [comment] 2016-04-07 04:19
Yes this is trill happening in the updated version the Play Store fed me yesterday.

As an example [this tweet's](https://twitter.com/simoncozens/status/717869222026567680) image shows up in the timeline but is blank in the fullscreen view.

**Comment by alerque** [comment] 2016-04-09 20:17
Once something fails and comes up blank closing and opening it doesn't help, but sometimes loading another media item from another tweet then going back will work. Also out of back to back tweets from the same user, phone, and client some might work while others fail so I'm going to suggest its not about the source image encoding.

**Closed** 2016-04-19 19:43 UTC
Labels: bug

**Comment by alerque** [comment] 2016-09-02 17:47
This seemed better for a while, but it's back. 80% or so of pictures are not rendering in full screen view. They work in the scaled down preview in the timeline and the links from fullscreen preview to open in another browser work, but the preview itself is blank.

**Comment by okoetter** [comment] 2016-09-05 15:43
I can confirm that. Problem is back now while it was better for some time.
