### ISSUE TITLE
Timeline not updating on pull-down

### ISSUE THREAD

**Issue by schwindp** [vanita5/twittnuker#93] opened 2016-04-10 12:25 UTC
Starting from 0.8.1 Tweetnuker doesn't Update the Timeline when pulling-down. It loads (shows the circle), but doesn't update. Only works if I forcefully kill the app.

**Comment by vanita5** [comment] 2016-04-10 19:47
Haven't had this problem so far. Any idea on how to reproduce this bug?

**Comment by schwindp** [comment] 2016-04-11 05:44
No idea, actually. No one else here seeing this behaviour? 

Android 5.1.1 on ONE E1003

**Comment by alerque** [comment] 2016-04-11 05:46
I'm not seeing this either, pulling down when I get to the top of the TL is my normal usage pattern and it's worked for me so far just as in the previous release.

The only related (but probably different) issue I've run into is not getting the same UI feedback while loading (especially loading skipped segments). It loads, but it doesn't tell you it's happening and sometimes I hit it a few times while waiting wondering if I'm connected.

**Comment by Grot4x** [comment] 2016-09-02 16:20
I can confirm this issue after having the app open in the background for a while pulling for update does not relay work. After closing the app by swiping it in this app overview thingy and reopening the app pulling for update works.

Version: 0.8.3
Android: 6.0.1

**Comment by alerque** [comment] 2016-09-02 17:39
This seems to be happening a lot more in the current release than it was even when this was reported.

**Comment by vanita5** [comment] 2016-12-13 19:01
Is this problem still present in 0.9?

**Comment by alerque** [comment] 2016-12-14 07:06
No, I don't think so. My memory isn't very scientific but I don't recall seeing this since the last update (a couple weeks ago).

**Comment by schwindp** [comment] 2016-12-14 07:12
I observed it only once for the last couple of weeks, just a few days ago. Let's pretend it's fixed though.

**Comment by Grot4x** [comment] 2016-12-14 07:22
It seems to be fixed didn't see it for quite some time :)

**Closed** 2016-12-16 13:24 UTC
Labels: bug
